#!/usr/bin/env ruby

require 'etc'

JOBS = Etc.nprocessors

$tests = ARGV
$failed = []
$jobs = {}

def run(test)
  path = File.absolute_path(test)
  pid = Process.spawn(path, out: '/dev/null')
  $jobs[pid] = test
end

$tests.pop(JOBS).each { |e| run(e) }

until $jobs.empty?
  pid, status = Process.wait2()
  test = $jobs[pid]
  puts '%s %s' % [test, status.success? ? 'ok' : 'fail']
  $failed << test unless status.success?
  $jobs.delete(pid)

  next_test = $tests.pop
  run(next_test) if next_test
end

puts "\n# Failed tests:" unless $failed.empty?
$failed.each do |test|
  puts test
end

exit $failed.empty?
